import { NextRequest } from 'next/server';
import connectDB from '@/lib/mongodb';
import { verifyAdmin } from '@/lib/auth';
import { successResponse, Errors } from '@/lib/apiResponse';
import MarketplaceTemplate from '@/models/MarketplaceTemplate';

/* ------------------------------------------------------------------ */
/*  10 Official Apple-level Marketplace Templates                     */
/* ------------------------------------------------------------------ */

const OFFICIAL_TEMPLATES = [
  /* ============================================================== */
  /*  1. Dental AI Assistant — Teal/cyan dark theme                 */
  /* ============================================================== */
  {
    name: 'Dental AI Assistant',
    slug: 'dental-ai-assistant',
    description:
      'A professional dental clinic chat assistant with a sleek teal/cyan dark theme. Helps patients book appointments, learn about services, check insurance compatibility, and get emergency care information. Perfect for dental practices of all sizes.',
    shortDescription: 'Professional dental clinic assistant with teal dark theme',
    niche: 'dental' as const,
    widgetType: 'ai_chat' as const,
    tags: ['dental', 'healthcare', 'appointments', 'insurance', 'dark-theme'],
    themeJson: {
      label: 'Dental AI Assistant',
      domain: '',
      fontUrl: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap',
      font: 'Inter',
      isDark: true,
      widgetW: '370px',
      widgetH: '540px',
      widgetMaxW: '370px',
      widgetMaxH: '540px',
      toggleSize: 'w-[58px] h-[58px]',
      toggleRadius: 'rounded-2xl',
      headerPad: 'px-6 py-5',
      nameSize: 'text-[15px]',
      avatarHeaderRound: 'rounded-xl',
      chatAvatarRound: 'rounded-lg',
      hasShine: true,
      headerFrom: '#0f2f2f',
      headerVia: '#134343',
      headerTo: '#0d1b2a',
      toggleFrom: '#0f2f2f',
      toggleVia: '#14b8a6',
      toggleTo: '#06b6d4',
      toggleShadow: '0 4px 20px rgba(20,184,166,0.4)',
      toggleHoverRgb: '20,184,166',
      sendFrom: '#14b8a6',
      sendTo: '#06b6d4',
      sendHoverFrom: '#0d9488',
      sendHoverTo: '#0891b2',
      userMsgFrom: '#115e59',
      userMsgTo: '#134e4a',
      userMsgShadow: '0 2px 8px rgba(20,184,166,0.15)',
      onlineDotBg: '#14b8a6',
      onlineDotBorder: '#0f2f2f',
      typingDot: '#14b8a6',
      avatarFrom: '#14b8a6',
      avatarTo: '#06b6d4',
      avatarBorder: '#0d9488',
      avatarIcon: '#ffffff',
      linkColor: '#2dd4bf',
      linkHover: '#5eead4',
      copyHover: '#14b8a6',
      copyActive: '#0d9488',
      chipBorder: '#115e59',
      chipFrom: '#0f2f2f',
      chipTo: '#134343',
      chipText: '#5eead4',
      chipHoverFrom: '#134343',
      chipHoverTo: '#115e59',
      chipHoverBorder: '#14b8a6',
      focusBorder: '#14b8a6',
      focusRing: '#14b8a6',
      focusRgb: '20,184,166',
      imgActiveBorder: '#14b8a6',
      imgActiveBg: '#115e59',
      imgActiveText: '#ffffff',
      imgHoverText: '#5eead4',
      imgHoverBorder: '#0d9488',
      imgHoverBg: '#134343',
      feedbackActive: '#14b8a6',
      feedbackHover: '#2dd4bf',
      cssPrimary: '#14b8a6',
      cssAccent: '#06b6d4',
      surfaceBg: '#0d1b2a',
      surfaceCard: '#122a3a',
      surfaceBorder: '#1e3a4a',
      surfaceInput: '#0f2535',
      surfaceInputFocus: '#163040',
      textPrimary: '#ffffff',
      textSecondary: '#9ca3af',
      textMuted: '#6b7280',
    },
    configJson: {
      botName: 'Dental AI',
      welcomeMessage: '\ud83d\udc4b Welcome! How can we help with your dental care today?',
      inputPlaceholder: 'Type your message...',
      quickReplies: ['Book appointment', 'Services & pricing', 'Insurance accepted?', 'Emergency care'],
      avatar: { type: 'emoji', emoji: '\ud83e\uddb7' },
      design: { position: 'bottom-right' },
      features: {
        sound: true,
        voiceInput: true,
        feedback: true,
        streaming: true,
        tts: false,
        autoLang: true,
        richCards: true,
        leadForm: false,
        memory: true,
        proactive: { delay: 15, message: 'Need help with a dental appointment? I can assist!' },
      },
      contacts: {},
    },
    knowledgeSample:
      'We offer general dentistry, cosmetic procedures, orthodontics, and emergency care. Open Mon-Sat 8am-6pm. Most insurance plans accepted. Same-day emergency appointments available.',
    authorId: 'winbix-official',
    authorName: 'WinBix AI',
    tier: 'official' as const,
    rating: 4.9,
    reviewCount: 0,
    installCount: 0,
    status: 'published' as const,
    screenshots: [],
    previewConfig: { primaryColor: '#14b8a6', isDark: true },
    publishedAt: new Date(),
  },

  /* ============================================================== */
  /*  2. Beauty Studio Chat — Rose/pink light theme                 */
  /* ============================================================== */
  {
    name: 'Beauty Studio Chat',
    slug: 'beauty-studio-chat',
    description:
      'An elegant rose/pink light theme beauty salon assistant. Helps clients book appointments, browse services, check pricing, and view portfolio work. Ideal for salons, spas, and beauty studios.',
    shortDescription: 'Elegant beauty salon assistant with rose pink light theme',
    niche: 'beauty' as const,
    widgetType: 'ai_chat' as const,
    tags: ['beauty', 'salon', 'spa', 'appointments', 'light-theme'],
    themeJson: {
      label: 'Beauty Studio Chat',
      domain: '',
      fontUrl: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap',
      font: 'Inter',
      isDark: false,
      widgetW: '370px',
      widgetH: '540px',
      widgetMaxW: '370px',
      widgetMaxH: '540px',
      toggleSize: 'w-[58px] h-[58px]',
      toggleRadius: 'rounded-2xl',
      headerPad: 'px-6 py-5',
      nameSize: 'text-[15px]',
      avatarHeaderRound: 'rounded-xl',
      chatAvatarRound: 'rounded-lg',
      hasShine: true,
      headerFrom: '#fce7f3',
      headerVia: '#fbcfe8',
      headerTo: '#f9a8d4',
      toggleFrom: '#ec4899',
      toggleVia: '#f472b6',
      toggleTo: '#f9a8d4',
      toggleShadow: '0 4px 20px rgba(236,72,153,0.35)',
      toggleHoverRgb: '236,72,153',
      sendFrom: '#ec4899',
      sendTo: '#f472b6',
      sendHoverFrom: '#db2777',
      sendHoverTo: '#ec4899',
      userMsgFrom: '#fce7f3',
      userMsgTo: '#fbcfe8',
      userMsgShadow: '0 2px 8px rgba(236,72,153,0.1)',
      onlineDotBg: '#ec4899',
      onlineDotBorder: '#fce7f3',
      typingDot: '#ec4899',
      avatarFrom: '#ec4899',
      avatarTo: '#f472b6',
      avatarBorder: '#db2777',
      avatarIcon: '#ffffff',
      linkColor: '#db2777',
      linkHover: '#be185d',
      copyHover: '#ec4899',
      copyActive: '#db2777',
      chipBorder: '#fbcfe8',
      chipFrom: '#fdf2f8',
      chipTo: '#fce7f3',
      chipText: '#be185d',
      chipHoverFrom: '#fce7f3',
      chipHoverTo: '#fbcfe8',
      chipHoverBorder: '#f472b6',
      focusBorder: '#ec4899',
      focusRing: '#ec4899',
      focusRgb: '236,72,153',
      imgActiveBorder: '#ec4899',
      imgActiveBg: '#fce7f3',
      imgActiveText: '#be185d',
      imgHoverText: '#db2777',
      imgHoverBorder: '#f472b6',
      imgHoverBg: '#fdf2f8',
      feedbackActive: '#ec4899',
      feedbackHover: '#f472b6',
      cssPrimary: '#ec4899',
      cssAccent: '#f472b6',
      surfaceBg: '#ffffff',
      surfaceCard: '#ffffff',
      surfaceBorder: '#e5e7eb',
      surfaceInput: '#f9fafb',
      surfaceInputFocus: '#ffffff',
      textPrimary: '#374151',
      textSecondary: '#9ca3af',
      textMuted: '#d1d5db',
    },
    configJson: {
      botName: 'Beauty Studio',
      welcomeMessage: '\ud83d\udc85 Welcome! Ready to book your next beauty session?',
      inputPlaceholder: 'Type your message...',
      quickReplies: ['Book appointment', 'View services', 'Check prices', 'See our portfolio'],
      avatar: { type: 'emoji', emoji: '\ud83d\udc85' },
      design: { position: 'bottom-right' },
      features: {
        sound: true,
        voiceInput: true,
        feedback: true,
        streaming: true,
        tts: false,
        autoLang: true,
        richCards: true,
        leadForm: false,
        memory: true,
        proactive: { delay: 15, message: 'Looking for a beauty appointment? Let me help!' },
      },
      contacts: {},
    },
    knowledgeSample:
      'Full-service beauty salon offering hair styling, manicure/pedicure, facials, waxing, and makeup. Open Tue-Sun 9am-8pm. Walk-ins welcome, appointments preferred.',
    authorId: 'winbix-official',
    authorName: 'WinBix AI',
    tier: 'official' as const,
    rating: 4.9,
    reviewCount: 0,
    installCount: 0,
    status: 'published' as const,
    screenshots: [],
    previewConfig: { primaryColor: '#ec4899', isDark: false },
    publishedAt: new Date(),
  },

  /* ============================================================== */
  /*  3. Restaurant Concierge — Red/orange dark theme               */
  /* ============================================================== */
  {
    name: 'Restaurant Concierge',
    slug: 'restaurant-concierge',
    description:
      'A warm red/orange dark theme restaurant assistant. Helps guests view menus, make reservations, discover daily specials, and explore dietary options. Great for restaurants, cafes, and bistros.',
    shortDescription: 'Warm restaurant assistant with red/orange dark theme',
    niche: 'restaurant' as const,
    widgetType: 'ai_chat' as const,
    tags: ['restaurant', 'food', 'reservations', 'menu', 'dark-theme'],
    themeJson: {
      label: 'Restaurant Concierge',
      domain: '',
      fontUrl: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap',
      font: 'Inter',
      isDark: true,
      widgetW: '370px',
      widgetH: '540px',
      widgetMaxW: '370px',
      widgetMaxH: '540px',
      toggleSize: 'w-[58px] h-[58px]',
      toggleRadius: 'rounded-2xl',
      headerPad: 'px-6 py-5',
      nameSize: 'text-[15px]',
      avatarHeaderRound: 'rounded-xl',
      chatAvatarRound: 'rounded-lg',
      hasShine: true,
      headerFrom: '#2a1010',
      headerVia: '#3b1515',
      headerTo: '#1a0808',
      toggleFrom: '#2a1010',
      toggleVia: '#ef4444',
      toggleTo: '#f97316',
      toggleShadow: '0 4px 20px rgba(239,68,68,0.4)',
      toggleHoverRgb: '239,68,68',
      sendFrom: '#ef4444',
      sendTo: '#f97316',
      sendHoverFrom: '#dc2626',
      sendHoverTo: '#ea580c',
      userMsgFrom: '#7f1d1d',
      userMsgTo: '#6c1a1a',
      userMsgShadow: '0 2px 8px rgba(239,68,68,0.15)',
      onlineDotBg: '#ef4444',
      onlineDotBorder: '#2a1010',
      typingDot: '#ef4444',
      avatarFrom: '#ef4444',
      avatarTo: '#f97316',
      avatarBorder: '#dc2626',
      avatarIcon: '#ffffff',
      linkColor: '#fca5a5',
      linkHover: '#fecaca',
      copyHover: '#ef4444',
      copyActive: '#dc2626',
      chipBorder: '#7f1d1d',
      chipFrom: '#2a1010',
      chipTo: '#3b1515',
      chipText: '#fca5a5',
      chipHoverFrom: '#3b1515',
      chipHoverTo: '#7f1d1d',
      chipHoverBorder: '#ef4444',
      focusBorder: '#ef4444',
      focusRing: '#ef4444',
      focusRgb: '239,68,68',
      imgActiveBorder: '#ef4444',
      imgActiveBg: '#7f1d1d',
      imgActiveText: '#ffffff',
      imgHoverText: '#fca5a5',
      imgHoverBorder: '#dc2626',
      imgHoverBg: '#3b1515',
      feedbackActive: '#ef4444',
      feedbackHover: '#f87171',
      cssPrimary: '#ef4444',
      cssAccent: '#f97316',
      surfaceBg: '#1a0808',
      surfaceCard: '#2a1010',
      surfaceBorder: '#4a1a1a',
      surfaceInput: '#200c0c',
      surfaceInputFocus: '#2e1212',
      textPrimary: '#ffffff',
      textSecondary: '#9ca3af',
      textMuted: '#6b7280',
    },
    configJson: {
      botName: 'Restaurant AI',
      welcomeMessage: '\ud83c\udf55 Welcome! Would you like to see our menu or make a reservation?',
      inputPlaceholder: 'Type your message...',
      quickReplies: ['View menu', 'Make reservation', "Today's specials", 'Dietary options'],
      avatar: { type: 'emoji', emoji: '\ud83c\udf55' },
      design: { position: 'bottom-right' },
      features: {
        sound: true,
        voiceInput: true,
        feedback: true,
        streaming: true,
        tts: false,
        autoLang: true,
        richCards: true,
        leadForm: false,
        memory: true,
        proactive: { delay: 15, message: 'Hungry? Check out our menu or reserve a table!' },
      },
      contacts: {},
    },
    knowledgeSample:
      'Award-winning restaurant featuring Mediterranean cuisine. Open daily 11am-11pm. Private dining available for groups of 8+. Vegan, gluten-free, and allergen-friendly options.',
    authorId: 'winbix-official',
    authorName: 'WinBix AI',
    tier: 'official' as const,
    rating: 4.9,
    reviewCount: 0,
    installCount: 0,
    status: 'published' as const,
    screenshots: [],
    previewConfig: { primaryColor: '#ef4444', isDark: true },
    publishedAt: new Date(),
  },

  /* ============================================================== */
  /*  4. Property Advisor — Emerald/green light theme               */
  /* ============================================================== */
  {
    name: 'Property Advisor',
    slug: 'property-advisor',
    description:
      'A fresh emerald/green light theme real estate assistant. Helps prospects search listings, schedule viewings, get property valuations, and explore mortgage options. Perfect for real estate agencies and brokers.',
    shortDescription: 'Fresh real estate assistant with emerald green light theme',
    niche: 'real_estate' as const,
    widgetType: 'ai_chat' as const,
    tags: ['real-estate', 'property', 'listings', 'mortgage', 'light-theme'],
    themeJson: {
      label: 'Property Advisor',
      domain: '',
      fontUrl: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap',
      font: 'Inter',
      isDark: false,
      widgetW: '370px',
      widgetH: '540px',
      widgetMaxW: '370px',
      widgetMaxH: '540px',
      toggleSize: 'w-[58px] h-[58px]',
      toggleRadius: 'rounded-2xl',
      headerPad: 'px-6 py-5',
      nameSize: 'text-[15px]',
      avatarHeaderRound: 'rounded-xl',
      chatAvatarRound: 'rounded-lg',
      hasShine: true,
      headerFrom: '#ecfdf5',
      headerVia: '#d1fae5',
      headerTo: '#a7f3d0',
      toggleFrom: '#10b981',
      toggleVia: '#34d399',
      toggleTo: '#6ee7b7',
      toggleShadow: '0 4px 20px rgba(16,185,129,0.35)',
      toggleHoverRgb: '16,185,129',
      sendFrom: '#10b981',
      sendTo: '#34d399',
      sendHoverFrom: '#059669',
      sendHoverTo: '#10b981',
      userMsgFrom: '#ecfdf5',
      userMsgTo: '#d1fae5',
      userMsgShadow: '0 2px 8px rgba(16,185,129,0.1)',
      onlineDotBg: '#10b981',
      onlineDotBorder: '#ecfdf5',
      typingDot: '#10b981',
      avatarFrom: '#10b981',
      avatarTo: '#34d399',
      avatarBorder: '#059669',
      avatarIcon: '#ffffff',
      linkColor: '#059669',
      linkHover: '#047857',
      copyHover: '#10b981',
      copyActive: '#059669',
      chipBorder: '#a7f3d0',
      chipFrom: '#ecfdf5',
      chipTo: '#d1fae5',
      chipText: '#047857',
      chipHoverFrom: '#d1fae5',
      chipHoverTo: '#a7f3d0',
      chipHoverBorder: '#34d399',
      focusBorder: '#10b981',
      focusRing: '#10b981',
      focusRgb: '16,185,129',
      imgActiveBorder: '#10b981',
      imgActiveBg: '#d1fae5',
      imgActiveText: '#047857',
      imgHoverText: '#059669',
      imgHoverBorder: '#34d399',
      imgHoverBg: '#ecfdf5',
      feedbackActive: '#10b981',
      feedbackHover: '#34d399',
      cssPrimary: '#10b981',
      cssAccent: '#34d399',
      surfaceBg: '#ffffff',
      surfaceCard: '#ffffff',
      surfaceBorder: '#e5e7eb',
      surfaceInput: '#f9fafb',
      surfaceInputFocus: '#ffffff',
      textPrimary: '#374151',
      textSecondary: '#9ca3af',
      textMuted: '#d1d5db',
    },
    configJson: {
      botName: 'Property Advisor',
      welcomeMessage: '\ud83c\udfe0 Welcome! Looking to buy, sell, or rent?',
      inputPlaceholder: 'Type your message...',
      quickReplies: ['Search listings', 'Schedule viewing', 'Get valuation', 'Mortgage info'],
      avatar: { type: 'emoji', emoji: '\ud83c\udfe0' },
      design: { position: 'bottom-right' },
      features: {
        sound: true,
        voiceInput: true,
        feedback: true,
        streaming: true,
        tts: false,
        autoLang: true,
        richCards: true,
        leadForm: false,
        memory: true,
        proactive: { delay: 15, message: 'Looking for your dream property? I can help you search!' },
      },
      contacts: {},
    },
    knowledgeSample:
      'Full-service real estate agency covering residential and commercial properties. Free property valuations. Virtual tours available. Pre-approved mortgage partners.',
    authorId: 'winbix-official',
    authorName: 'WinBix AI',
    tier: 'official' as const,
    rating: 4.9,
    reviewCount: 0,
    installCount: 0,
    status: 'published' as const,
    screenshots: [],
    previewConfig: { primaryColor: '#10b981', isDark: false },
    publishedAt: new Date(),
  },

  /* ============================================================== */
  /*  5. Shop Assistant — Violet/purple dark theme                  */
  /* ============================================================== */
  {
    name: 'Shop Assistant',
    slug: 'shop-assistant',
    description:
      'A modern violet/purple dark theme e-commerce assistant. Helps shoppers track orders, browse products, understand return policies, and reach support. Ideal for online stores and marketplaces.',
    shortDescription: 'Modern e-commerce assistant with violet purple dark theme',
    niche: 'ecommerce' as const,
    widgetType: 'ai_chat' as const,
    tags: ['ecommerce', 'shopping', 'orders', 'support', 'dark-theme'],
    themeJson: {
      label: 'Shop Assistant',
      domain: '',
      fontUrl: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap',
      font: 'Inter',
      isDark: true,
      widgetW: '370px',
      widgetH: '540px',
      widgetMaxW: '370px',
      widgetMaxH: '540px',
      toggleSize: 'w-[58px] h-[58px]',
      toggleRadius: 'rounded-2xl',
      headerPad: 'px-6 py-5',
      nameSize: 'text-[15px]',
      avatarHeaderRound: 'rounded-xl',
      chatAvatarRound: 'rounded-lg',
      hasShine: true,
      headerFrom: '#1e1035',
      headerVia: '#2d1b4e',
      headerTo: '#150c25',
      toggleFrom: '#1e1035',
      toggleVia: '#8b5cf6',
      toggleTo: '#a78bfa',
      toggleShadow: '0 4px 20px rgba(139,92,246,0.4)',
      toggleHoverRgb: '139,92,246',
      sendFrom: '#8b5cf6',
      sendTo: '#a78bfa',
      sendHoverFrom: '#7c3aed',
      sendHoverTo: '#8b5cf6',
      userMsgFrom: '#4c1d95',
      userMsgTo: '#3b0f80',
      userMsgShadow: '0 2px 8px rgba(139,92,246,0.15)',
      onlineDotBg: '#8b5cf6',
      onlineDotBorder: '#1e1035',
      typingDot: '#8b5cf6',
      avatarFrom: '#8b5cf6',
      avatarTo: '#a78bfa',
      avatarBorder: '#7c3aed',
      avatarIcon: '#ffffff',
      linkColor: '#c4b5fd',
      linkHover: '#ddd6fe',
      copyHover: '#8b5cf6',
      copyActive: '#7c3aed',
      chipBorder: '#4c1d95',
      chipFrom: '#1e1035',
      chipTo: '#2d1b4e',
      chipText: '#c4b5fd',
      chipHoverFrom: '#2d1b4e',
      chipHoverTo: '#4c1d95',
      chipHoverBorder: '#8b5cf6',
      focusBorder: '#8b5cf6',
      focusRing: '#8b5cf6',
      focusRgb: '139,92,246',
      imgActiveBorder: '#8b5cf6',
      imgActiveBg: '#4c1d95',
      imgActiveText: '#ffffff',
      imgHoverText: '#c4b5fd',
      imgHoverBorder: '#7c3aed',
      imgHoverBg: '#2d1b4e',
      feedbackActive: '#8b5cf6',
      feedbackHover: '#a78bfa',
      cssPrimary: '#8b5cf6',
      cssAccent: '#a78bfa',
      surfaceBg: '#150c25',
      surfaceCard: '#1e1035',
      surfaceBorder: '#3b1f6e',
      surfaceInput: '#1a0e30',
      surfaceInputFocus: '#24153f',
      textPrimary: '#ffffff',
      textSecondary: '#9ca3af',
      textMuted: '#6b7280',
    },
    configJson: {
      botName: 'Shop Assistant',
      welcomeMessage: '\ud83d\uded2 Hi there! How can I help you shop today?',
      inputPlaceholder: 'Type your message...',
      quickReplies: ['Track my order', 'Browse products', 'Return policy', 'Contact support'],
      avatar: { type: 'emoji', emoji: '\ud83d\uded2' },
      design: { position: 'bottom-right' },
      features: {
        sound: true,
        voiceInput: true,
        feedback: true,
        streaming: true,
        tts: false,
        autoLang: true,
        richCards: true,
        leadForm: false,
        memory: true,
        proactive: { delay: 15, message: 'Need help finding something? I can assist!' },
      },
      contacts: {},
    },
    knowledgeSample:
      'Online store with 10,000+ products. Free shipping on orders over $50. 30-day returns. Same-day delivery available in metro areas. Loyalty rewards program.',
    authorId: 'winbix-official',
    authorName: 'WinBix AI',
    tier: 'official' as const,
    rating: 4.9,
    reviewCount: 0,
    installCount: 0,
    status: 'published' as const,
    screenshots: [],
    previewConfig: { primaryColor: '#8b5cf6', isDark: true },
    publishedAt: new Date(),
  },

  /* ============================================================== */
  /*  6. SaaS Support Bot — Indigo/blue dark theme                  */
  /* ============================================================== */
  {
    name: 'SaaS Support Bot',
    slug: 'saas-support-bot',
    description:
      'A technical indigo/blue dark theme SaaS support assistant. Helps users explore pricing, book demos, access API documentation, and report issues. Built for SaaS companies and tech startups.',
    shortDescription: 'Technical SaaS support assistant with indigo blue dark theme',
    niche: 'saas' as const,
    widgetType: 'ai_chat' as const,
    tags: ['saas', 'tech', 'support', 'api', 'dark-theme'],
    themeJson: {
      label: 'SaaS Support Bot',
      domain: '',
      fontUrl: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap',
      font: 'Inter',
      isDark: true,
      widgetW: '370px',
      widgetH: '540px',
      widgetMaxW: '370px',
      widgetMaxH: '540px',
      toggleSize: 'w-[58px] h-[58px]',
      toggleRadius: 'rounded-2xl',
      headerPad: 'px-6 py-5',
      nameSize: 'text-[15px]',
      avatarHeaderRound: 'rounded-xl',
      chatAvatarRound: 'rounded-lg',
      hasShine: true,
      headerFrom: '#0f1629',
      headerVia: '#1a2340',
      headerTo: '#0c1120',
      toggleFrom: '#0f1629',
      toggleVia: '#6366f1',
      toggleTo: '#818cf8',
      toggleShadow: '0 4px 20px rgba(99,102,241,0.4)',
      toggleHoverRgb: '99,102,241',
      sendFrom: '#6366f1',
      sendTo: '#818cf8',
      sendHoverFrom: '#4f46e5',
      sendHoverTo: '#6366f1',
      userMsgFrom: '#312e81',
      userMsgTo: '#272470',
      userMsgShadow: '0 2px 8px rgba(99,102,241,0.15)',
      onlineDotBg: '#6366f1',
      onlineDotBorder: '#0f1629',
      typingDot: '#6366f1',
      avatarFrom: '#6366f1',
      avatarTo: '#818cf8',
      avatarBorder: '#4f46e5',
      avatarIcon: '#ffffff',
      linkColor: '#a5b4fc',
      linkHover: '#c7d2fe',
      copyHover: '#6366f1',
      copyActive: '#4f46e5',
      chipBorder: '#312e81',
      chipFrom: '#0f1629',
      chipTo: '#1a2340',
      chipText: '#a5b4fc',
      chipHoverFrom: '#1a2340',
      chipHoverTo: '#312e81',
      chipHoverBorder: '#6366f1',
      focusBorder: '#6366f1',
      focusRing: '#6366f1',
      focusRgb: '99,102,241',
      imgActiveBorder: '#6366f1',
      imgActiveBg: '#312e81',
      imgActiveText: '#ffffff',
      imgHoverText: '#a5b4fc',
      imgHoverBorder: '#4f46e5',
      imgHoverBg: '#1a2340',
      feedbackActive: '#6366f1',
      feedbackHover: '#818cf8',
      cssPrimary: '#6366f1',
      cssAccent: '#818cf8',
      surfaceBg: '#0c1120',
      surfaceCard: '#0f1629',
      surfaceBorder: '#1e2d50',
      surfaceInput: '#0e1425',
      surfaceInputFocus: '#151e38',
      textPrimary: '#ffffff',
      textSecondary: '#9ca3af',
      textMuted: '#6b7280',
    },
    configJson: {
      botName: 'SaaS Support',
      welcomeMessage: '\ud83d\udcbb Welcome! Need help with our platform?',
      inputPlaceholder: 'Type your message...',
      quickReplies: ['View pricing', 'Book a demo', 'API documentation', 'Report an issue'],
      avatar: { type: 'emoji', emoji: '\ud83d\udcbb' },
      design: { position: 'bottom-right' },
      features: {
        sound: true,
        voiceInput: true,
        feedback: true,
        streaming: true,
        tts: false,
        autoLang: true,
        richCards: true,
        leadForm: false,
        memory: true,
        proactive: { delay: 15, message: "Need help with our platform? I'm here to assist!" },
      },
      contacts: {},
    },
    knowledgeSample:
      'Cloud-based SaaS platform for team collaboration. Free tier available. 99.9% uptime SLA. REST API with SDKs for Python, Node.js, and Go. 24/7 support for Enterprise plans.',
    authorId: 'winbix-official',
    authorName: 'WinBix AI',
    tier: 'official' as const,
    rating: 4.9,
    reviewCount: 0,
    installCount: 0,
    status: 'published' as const,
    screenshots: [],
    previewConfig: { primaryColor: '#6366f1', isDark: true },
    publishedAt: new Date(),
  },

  /* ============================================================== */
  /*  7. Hotel Concierge — Amber/gold dark theme                    */
  /* ============================================================== */
  {
    name: 'Hotel Concierge',
    slug: 'hotel-concierge',
    description:
      'A luxurious amber/gold dark theme hotel concierge assistant. Helps guests book rooms, order room service, discover local attractions, and manage check-in. Perfect for hotels and resorts.',
    shortDescription: 'Luxurious hotel concierge assistant with amber gold dark theme',
    niche: 'hotel' as const,
    widgetType: 'ai_chat' as const,
    tags: ['hotel', 'travel', 'hospitality', 'concierge', 'dark-theme'],
    themeJson: {
      label: 'Hotel Concierge',
      domain: '',
      fontUrl: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap',
      font: 'Inter',
      isDark: true,
      widgetW: '370px',
      widgetH: '540px',
      widgetMaxW: '370px',
      widgetMaxH: '540px',
      toggleSize: 'w-[58px] h-[58px]',
      toggleRadius: 'rounded-2xl',
      headerPad: 'px-6 py-5',
      nameSize: 'text-[15px]',
      avatarHeaderRound: 'rounded-xl',
      chatAvatarRound: 'rounded-lg',
      hasShine: true,
      headerFrom: '#2a2008',
      headerVia: '#3b2e10',
      headerTo: '#1a1505',
      toggleFrom: '#2a2008',
      toggleVia: '#f59e0b',
      toggleTo: '#fbbf24',
      toggleShadow: '0 4px 20px rgba(245,158,11,0.4)',
      toggleHoverRgb: '245,158,11',
      sendFrom: '#f59e0b',
      sendTo: '#fbbf24',
      sendHoverFrom: '#d97706',
      sendHoverTo: '#f59e0b',
      userMsgFrom: '#78350f',
      userMsgTo: '#653008',
      userMsgShadow: '0 2px 8px rgba(245,158,11,0.15)',
      onlineDotBg: '#f59e0b',
      onlineDotBorder: '#2a2008',
      typingDot: '#f59e0b',
      avatarFrom: '#f59e0b',
      avatarTo: '#fbbf24',
      avatarBorder: '#d97706',
      avatarIcon: '#ffffff',
      linkColor: '#fcd34d',
      linkHover: '#fde68a',
      copyHover: '#f59e0b',
      copyActive: '#d97706',
      chipBorder: '#78350f',
      chipFrom: '#2a2008',
      chipTo: '#3b2e10',
      chipText: '#fcd34d',
      chipHoverFrom: '#3b2e10',
      chipHoverTo: '#78350f',
      chipHoverBorder: '#f59e0b',
      focusBorder: '#f59e0b',
      focusRing: '#f59e0b',
      focusRgb: '245,158,11',
      imgActiveBorder: '#f59e0b',
      imgActiveBg: '#78350f',
      imgActiveText: '#ffffff',
      imgHoverText: '#fcd34d',
      imgHoverBorder: '#d97706',
      imgHoverBg: '#3b2e10',
      feedbackActive: '#f59e0b',
      feedbackHover: '#fbbf24',
      cssPrimary: '#f59e0b',
      cssAccent: '#fbbf24',
      surfaceBg: '#1a1505',
      surfaceCard: '#2a2008',
      surfaceBorder: '#4a3810',
      surfaceInput: '#201a08',
      surfaceInputFocus: '#2e2510',
      textPrimary: '#ffffff',
      textSecondary: '#9ca3af',
      textMuted: '#6b7280',
    },
    configJson: {
      botName: 'Hotel Concierge',
      welcomeMessage: '\ud83c\udfe8 Welcome! How may I assist you during your stay?',
      inputPlaceholder: 'Type your message...',
      quickReplies: ['Book a room', 'Room service', 'Local attractions', 'Check-in info'],
      avatar: { type: 'emoji', emoji: '\ud83c\udfe8' },
      design: { position: 'bottom-right' },
      features: {
        sound: true,
        voiceInput: true,
        feedback: true,
        streaming: true,
        tts: false,
        autoLang: true,
        richCards: true,
        leadForm: false,
        memory: true,
        proactive: { delay: 15, message: "Need anything during your stay? I'm here to help!" },
      },
      contacts: {},
    },
    knowledgeSample:
      'Luxury 5-star hotel in the city center. 200 rooms & suites. Spa, pool, fitness center, 3 restaurants. Airport shuttle available. Free Wi-Fi. Pet-friendly rooms available.',
    authorId: 'winbix-official',
    authorName: 'WinBix AI',
    tier: 'official' as const,
    rating: 4.9,
    reviewCount: 0,
    installCount: 0,
    status: 'published' as const,
    screenshots: [],
    previewConfig: { primaryColor: '#f59e0b', isDark: true },
    publishedAt: new Date(),
  },

  /* ============================================================== */
  /*  8. Fitness Coach — Orange/red light theme                     */
  /* ============================================================== */
  {
    name: 'Fitness Coach',
    slug: 'fitness-coach',
    description:
      'An energetic orange/red light theme fitness assistant. Helps members view class schedules, explore membership plans, book personal training, and sign up for free trials. Great for gyms and fitness studios.',
    shortDescription: 'Energetic fitness assistant with orange light theme',
    niche: 'fitness' as const,
    widgetType: 'ai_chat' as const,
    tags: ['fitness', 'gym', 'training', 'classes', 'light-theme'],
    themeJson: {
      label: 'Fitness Coach',
      domain: '',
      fontUrl: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap',
      font: 'Inter',
      isDark: false,
      widgetW: '370px',
      widgetH: '540px',
      widgetMaxW: '370px',
      widgetMaxH: '540px',
      toggleSize: 'w-[58px] h-[58px]',
      toggleRadius: 'rounded-2xl',
      headerPad: 'px-6 py-5',
      nameSize: 'text-[15px]',
      avatarHeaderRound: 'rounded-xl',
      chatAvatarRound: 'rounded-lg',
      hasShine: true,
      headerFrom: '#fff7ed',
      headerVia: '#ffedd5',
      headerTo: '#fed7aa',
      toggleFrom: '#f97316',
      toggleVia: '#fb923c',
      toggleTo: '#fdba74',
      toggleShadow: '0 4px 20px rgba(249,115,22,0.35)',
      toggleHoverRgb: '249,115,22',
      sendFrom: '#f97316',
      sendTo: '#fb923c',
      sendHoverFrom: '#ea580c',
      sendHoverTo: '#f97316',
      userMsgFrom: '#fff7ed',
      userMsgTo: '#ffedd5',
      userMsgShadow: '0 2px 8px rgba(249,115,22,0.1)',
      onlineDotBg: '#f97316',
      onlineDotBorder: '#fff7ed',
      typingDot: '#f97316',
      avatarFrom: '#f97316',
      avatarTo: '#fb923c',
      avatarBorder: '#ea580c',
      avatarIcon: '#ffffff',
      linkColor: '#ea580c',
      linkHover: '#c2410c',
      copyHover: '#f97316',
      copyActive: '#ea580c',
      chipBorder: '#fed7aa',
      chipFrom: '#fff7ed',
      chipTo: '#ffedd5',
      chipText: '#c2410c',
      chipHoverFrom: '#ffedd5',
      chipHoverTo: '#fed7aa',
      chipHoverBorder: '#fb923c',
      focusBorder: '#f97316',
      focusRing: '#f97316',
      focusRgb: '249,115,22',
      imgActiveBorder: '#f97316',
      imgActiveBg: '#ffedd5',
      imgActiveText: '#c2410c',
      imgHoverText: '#ea580c',
      imgHoverBorder: '#fb923c',
      imgHoverBg: '#fff7ed',
      feedbackActive: '#f97316',
      feedbackHover: '#fb923c',
      cssPrimary: '#f97316',
      cssAccent: '#fb923c',
      surfaceBg: '#ffffff',
      surfaceCard: '#ffffff',
      surfaceBorder: '#e5e7eb',
      surfaceInput: '#f9fafb',
      surfaceInputFocus: '#ffffff',
      textPrimary: '#374151',
      textSecondary: '#9ca3af',
      textMuted: '#d1d5db',
    },
    configJson: {
      botName: 'Fitness Coach',
      welcomeMessage: "\ud83d\udcaa Ready to crush your fitness goals? Let's get started!",
      inputPlaceholder: 'Type your message...',
      quickReplies: ['Class schedule', 'Membership plans', 'Personal training', 'Free trial'],
      avatar: { type: 'emoji', emoji: '\ud83d\udcaa' },
      design: { position: 'bottom-right' },
      features: {
        sound: true,
        voiceInput: true,
        feedback: true,
        streaming: true,
        tts: false,
        autoLang: true,
        richCards: true,
        leadForm: false,
        memory: true,
        proactive: { delay: 15, message: 'Ready to start your fitness journey? Ask me anything!' },
      },
      contacts: {},
    },
    knowledgeSample:
      'Modern fitness center with 50+ weekly classes. CrossFit, yoga, spinning, boxing, and HIIT. Personal trainers available. Open 5am-11pm daily. Student and corporate discounts.',
    authorId: 'winbix-official',
    authorName: 'WinBix AI',
    tier: 'official' as const,
    rating: 4.9,
    reviewCount: 0,
    installCount: 0,
    status: 'published' as const,
    screenshots: [],
    previewConfig: { primaryColor: '#f97316', isDark: false },
    publishedAt: new Date(),
  },

  /* ============================================================== */
  /*  9. Legal Advisor — Navy/slate dark theme                      */
  /* ============================================================== */
  {
    name: 'Legal Advisor',
    slug: 'legal-advisor',
    description:
      'A professional navy/slate dark theme legal assistant. Helps clients book consultations, learn about practice areas, access legal FAQs, and connect with attorneys. Built for law firms and legal practices.',
    shortDescription: 'Professional legal assistant with navy slate dark theme',
    niche: 'legal' as const,
    widgetType: 'ai_chat' as const,
    tags: ['legal', 'law-firm', 'consultation', 'attorney', 'dark-theme'],
    themeJson: {
      label: 'Legal Advisor',
      domain: '',
      fontUrl: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap',
      font: 'Inter',
      isDark: true,
      widgetW: '370px',
      widgetH: '540px',
      widgetMaxW: '370px',
      widgetMaxH: '540px',
      toggleSize: 'w-[58px] h-[58px]',
      toggleRadius: 'rounded-2xl',
      headerPad: 'px-6 py-5',
      nameSize: 'text-[15px]',
      avatarHeaderRound: 'rounded-xl',
      chatAvatarRound: 'rounded-lg',
      hasShine: true,
      headerFrom: '#0f172a',
      headerVia: '#1e293b',
      headerTo: '#0c1220',
      toggleFrom: '#0f172a',
      toggleVia: '#64748b',
      toggleTo: '#94a3b8',
      toggleShadow: '0 4px 20px rgba(100,116,139,0.4)',
      toggleHoverRgb: '100,116,139',
      sendFrom: '#64748b',
      sendTo: '#94a3b8',
      sendHoverFrom: '#475569',
      sendHoverTo: '#64748b',
      userMsgFrom: '#334155',
      userMsgTo: '#293548',
      userMsgShadow: '0 2px 8px rgba(100,116,139,0.15)',
      onlineDotBg: '#64748b',
      onlineDotBorder: '#0f172a',
      typingDot: '#64748b',
      avatarFrom: '#64748b',
      avatarTo: '#94a3b8',
      avatarBorder: '#475569',
      avatarIcon: '#ffffff',
      linkColor: '#cbd5e1',
      linkHover: '#e2e8f0',
      copyHover: '#64748b',
      copyActive: '#475569',
      chipBorder: '#334155',
      chipFrom: '#0f172a',
      chipTo: '#1e293b',
      chipText: '#cbd5e1',
      chipHoverFrom: '#1e293b',
      chipHoverTo: '#334155',
      chipHoverBorder: '#64748b',
      focusBorder: '#64748b',
      focusRing: '#64748b',
      focusRgb: '100,116,139',
      imgActiveBorder: '#64748b',
      imgActiveBg: '#334155',
      imgActiveText: '#ffffff',
      imgHoverText: '#cbd5e1',
      imgHoverBorder: '#475569',
      imgHoverBg: '#1e293b',
      feedbackActive: '#64748b',
      feedbackHover: '#94a3b8',
      cssPrimary: '#64748b',
      cssAccent: '#94a3b8',
      surfaceBg: '#0c1220',
      surfaceCard: '#0f172a',
      surfaceBorder: '#1e293b',
      surfaceInput: '#0e1525',
      surfaceInputFocus: '#151e30',
      textPrimary: '#ffffff',
      textSecondary: '#9ca3af',
      textMuted: '#6b7280',
    },
    configJson: {
      botName: 'Legal Advisor',
      welcomeMessage: '\u2696\ufe0f Welcome. How can our legal team assist you today?',
      inputPlaceholder: 'Type your message...',
      quickReplies: ['Book consultation', 'Practice areas', 'Legal FAQ', 'Contact attorney'],
      avatar: { type: 'emoji', emoji: '\u2696\ufe0f' },
      design: { position: 'bottom-right' },
      features: {
        sound: true,
        voiceInput: true,
        feedback: true,
        streaming: true,
        tts: false,
        autoLang: true,
        richCards: true,
        leadForm: false,
        memory: true,
        proactive: { delay: 15, message: 'Need legal guidance? Schedule a free consultation.' },
      },
      contacts: {},
    },
    knowledgeSample:
      'Full-service law firm specializing in business law, family law, real estate, and immigration. Free 30-minute initial consultation. Multilingual attorneys. Confidential and professional.',
    authorId: 'winbix-official',
    authorName: 'WinBix AI',
    tier: 'official' as const,
    rating: 4.9,
    reviewCount: 0,
    installCount: 0,
    status: 'published' as const,
    screenshots: [],
    previewConfig: { primaryColor: '#64748b', isDark: true },
    publishedAt: new Date(),
  },

  /* ============================================================== */
  /*  10. Auto Service Hub — Charcoal/silver light theme            */
  /* ============================================================== */
  {
    name: 'Auto Service Hub',
    slug: 'auto-service-hub',
    description:
      'A clean charcoal/silver light theme automotive assistant. Helps customers book service appointments, inquire about parts, get quotes, and explore financing options. Ideal for auto shops and dealerships.',
    shortDescription: 'Clean auto service assistant with charcoal silver light theme',
    niche: 'auto' as const,
    widgetType: 'ai_chat' as const,
    tags: ['auto', 'automotive', 'service', 'parts', 'light-theme'],
    themeJson: {
      label: 'Auto Service Hub',
      domain: '',
      fontUrl: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap',
      font: 'Inter',
      isDark: false,
      widgetW: '370px',
      widgetH: '540px',
      widgetMaxW: '370px',
      widgetMaxH: '540px',
      toggleSize: 'w-[58px] h-[58px]',
      toggleRadius: 'rounded-2xl',
      headerPad: 'px-6 py-5',
      nameSize: 'text-[15px]',
      avatarHeaderRound: 'rounded-xl',
      chatAvatarRound: 'rounded-lg',
      hasShine: true,
      headerFrom: '#f3f4f6',
      headerVia: '#e5e7eb',
      headerTo: '#d1d5db',
      toggleFrom: '#6b7280',
      toggleVia: '#9ca3af',
      toggleTo: '#d1d5db',
      toggleShadow: '0 4px 20px rgba(107,114,128,0.35)',
      toggleHoverRgb: '107,114,128',
      sendFrom: '#6b7280',
      sendTo: '#9ca3af',
      sendHoverFrom: '#4b5563',
      sendHoverTo: '#6b7280',
      userMsgFrom: '#f3f4f6',
      userMsgTo: '#e5e7eb',
      userMsgShadow: '0 2px 8px rgba(107,114,128,0.1)',
      onlineDotBg: '#6b7280',
      onlineDotBorder: '#f3f4f6',
      typingDot: '#6b7280',
      avatarFrom: '#6b7280',
      avatarTo: '#9ca3af',
      avatarBorder: '#4b5563',
      avatarIcon: '#ffffff',
      linkColor: '#4b5563',
      linkHover: '#374151',
      copyHover: '#6b7280',
      copyActive: '#4b5563',
      chipBorder: '#d1d5db',
      chipFrom: '#f9fafb',
      chipTo: '#f3f4f6',
      chipText: '#374151',
      chipHoverFrom: '#f3f4f6',
      chipHoverTo: '#e5e7eb',
      chipHoverBorder: '#9ca3af',
      focusBorder: '#6b7280',
      focusRing: '#6b7280',
      focusRgb: '107,114,128',
      imgActiveBorder: '#6b7280',
      imgActiveBg: '#e5e7eb',
      imgActiveText: '#374151',
      imgHoverText: '#4b5563',
      imgHoverBorder: '#9ca3af',
      imgHoverBg: '#f3f4f6',
      feedbackActive: '#6b7280',
      feedbackHover: '#9ca3af',
      cssPrimary: '#6b7280',
      cssAccent: '#9ca3af',
      surfaceBg: '#ffffff',
      surfaceCard: '#ffffff',
      surfaceBorder: '#e5e7eb',
      surfaceInput: '#f9fafb',
      surfaceInputFocus: '#ffffff',
      textPrimary: '#374151',
      textSecondary: '#9ca3af',
      textMuted: '#d1d5db',
    },
    configJson: {
      botName: 'Auto Service',
      welcomeMessage: '\ud83d\ude97 Welcome! Need service, parts, or financing help?',
      inputPlaceholder: 'Type your message...',
      quickReplies: ['Book service', 'Parts inquiry', 'Get a quote', 'Financing options'],
      avatar: { type: 'emoji', emoji: '\ud83d\ude97' },
      design: { position: 'bottom-right' },
      features: {
        sound: true,
        voiceInput: true,
        feedback: true,
        streaming: true,
        tts: false,
        autoLang: true,
        richCards: true,
        leadForm: false,
        memory: true,
        proactive: { delay: 15, message: 'Need auto service or parts? I can help you out!' },
      },
      contacts: {},
    },
    knowledgeSample:
      'Certified auto service center for all makes and models. Oil changes, brake service, engine diagnostics, body work. Genuine OEM parts. Free estimates. Loaner vehicles available.',
    authorId: 'winbix-official',
    authorName: 'WinBix AI',
    tier: 'official' as const,
    rating: 4.9,
    reviewCount: 0,
    installCount: 0,
    status: 'published' as const,
    screenshots: [],
    previewConfig: { primaryColor: '#6b7280', isDark: false },
    publishedAt: new Date(),
  },
];

/* ------------------------------------------------------------------ */
/*  POST /api/marketplace/seed — Admin-only seed endpoint             */
/* ------------------------------------------------------------------ */

export async function POST(request: NextRequest) {
  const auth = await verifyAdmin(request);
  if (!auth.authenticated) return auth.response;

  await connectDB();

  let seeded = 0;
  for (const tmpl of OFFICIAL_TEMPLATES) {
    const exists = await MarketplaceTemplate.findOne({ slug: tmpl.slug });
    if (!exists) {
      await MarketplaceTemplate.create(tmpl);
      seeded++;
    }
  }

  return successResponse({ seeded, total: OFFICIAL_TEMPLATES.length }, `Seeded ${seeded} templates`);
}
